# Generated by Django 5.2.8 on 2025-11-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("company", models.CharField(blank=True, max_length=150, null=True)),
                ("address", models.TextField()),
                ("meet_time", models.DateField(blank=True, null=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("plan_price", models.CharField(max_length=50)),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
